#!/bin/bash

TOP_DIR=$( readlink -n -f $(dirname $0) )

# detect whether boost/bootstrap.sh has been executed yet and if not, do so
if test -f "${TOP_DIR}/boost/bjam" -a -x "${TOP_DIR}/boost/bjam" ; then
    echo boost/bjam  already built
else
    echo Note:  any options passed in on the command line will be passed to
    echo        boost/bootstrap.sh
    echo building boost/bjam...
    pushd ${TOP_DIR}/boost 2> /dev/null
    ./bootstrap.sh "$@"
    popd 2> /dev/null
fi

#need to make sure that the boost-build path is set
export BOOST_BUILD_PATH=${TOP_DIR}/boost/tools/build/v2/

# put the boost sub-project into the path so that we can get bjam correctly
export PATH=${TOP_DIR}/boost:$PATH

echo "Entering login shell with the proper environment changes"
exec $SHELL
